version: '3'

services:
  demo-math:
    image: golang:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./demo-math"
    ports:
      - "777:1323"
    restart: on-failure
